name: base_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  micro_core:
    path: ../micro_core
  micro_app_details:
    path: ../micro_app_details
  micro_app_home:
    path: ../micro_app_home
  micro_dependency:
    path: ../micro_dependency
  micro_common:
    path: ../micro_common


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true




